### ISSUE TITLE
Facing issue while running the classificaton interpretation

### ISSUE THREAD

**Issue by balajib363** [anhquan0412/animation-classification#4]
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/balaji/anaconda3/envs/mooid/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/balaji/anaconda3/envs/mooid/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/balaji/anaconda3/envs/mooid/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/balaji/anaconda3/envs/mooid/lib/python3.6/site-packages/fastai/data_block.py", line 655, in __getitem__
    if self.item is None: x,y = self.x[idxs],self.y[idxs]
  File "/home/balaji/anaconda3/envs/mooid/lib/python3.6/site-packages/fastai/data_block.py", line 120, in __getitem__
    if isinstance(idxs, Integral): return self.get(idxs)
  File "/home/balaji/anaconda3/envs/mooid/lib/python3.6/site-packages/fastai/vision/data.py", line 270, in get
    fn = super().get(i)
  File "/home/balaji/anaconda3/envs/mooid/lib/python3.6/site-packages/fastai/data_block.py", line 75, in get
    return self.items[i]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by balajib363** [comment]
Let me know, how to handle this.
